### ISSUE TITLE
undefined when evaluating 'window.location.href'

### ISSUE THREAD

**Issue by khuang-citylift** [Avery246813579/Stripe-Terminal#1]
Hi Avery,

```
import StripeTerminal from 'stripe-terminal';
let Instance = StripeTerminal();
```

When trying to instantiate StripeTerminal, I am getting an undefined error for 'window.location.href'. Does that need to be replaced with a '-1' as well?

Thank you,
Kevin

**Comment by Avery246813579** [comment]
Hi Kevin, 

Are you using this for the bluetooth reader or with the wifi reader?

If you are using the bluetooth reader I would delegate you to use https://github.com/theopolisme/react-native-stripe-terminal

If not I can continue to help you.

Thanks,
Avery

**Comment by khuang-citylift** [comment]
Hi Avery,

I'm using this with the Verifone P400 WiFi Reader. I am using Expo for my React Native project so unfortunately, theopolisme's module would not work because it would require me to eject from Expo to install native dependencies.

Thanks,
Kevin

**Comment by Avery246813579** [comment]
@khuang-citylift are you still looking for this module? Everything should actually work now.

**Comment by Avery246813579** [comment]
Closed unless problems come up in the future.
